Socket io
Code-the-Dream-School/cc-prac-team2-front pull request #18
Opened 2023-06-08 02:57 UTC by Miminiverse

This PR contains:

1. Update login and register API (change from /users to /account)
2. Show Welcome page in Chat Page (loading page)
3. Update time in every messages
4. Connect users to socketIO
6. Sending real time messages with SocketIO

2023-06-08 12:36 UTC, royemosby requested changes
Code looks pretty good. I did have 2 questions inline and a comment about setting the timezone. Things don't necessarily need to change but I would need more context around those.

2023-06-08 12:36 UTC, royemosby commented on src/components/ChatContainer.tsx
> +                    _id: uuidv4(),
Same question as above

2023-06-08 12:36 UTC, royemosby commented on src/components/ChatWelcome.tsx
> +          <p>Welcome to TALCKATOO chat app!</p>
Is it "TALCKATOO" or "TALKATOO"? I've seen both spellings during our Zoom meetings.

2023-06-08 12:36 UTC, royemosby commented on src/util/getTime.tsx
> +    const estTime = moment(utcTime).utcOffset(-4).format('hh:mm A');
Just so you're aware, this hardwires in Eastern Daylight Time regardless of where the user is.

2023-06-08 17:57 UTC, Miminiverse commented on src/components/ChatContainer.tsx
> +                _id: uuidv4(),
Hi Roy, this is a good question,  I set it up because in this POST request, the backend didn't send back anything, so I put the id in just so it matches with the messages in the GET messages request. I believe I don't really need it, and I think we will discuss with the backend team to see if they can send me back info from this POST message request, then I will just use those data instead of making my own (same for the createdAt)

2023-06-08 17:58 UTC, Miminiverse commented on src/components/ChatWelcome.tsx
> +          <p>Welcome to TALCKATOO chat app!</p>
TALCKATOO here we go :)

2023-06-08 18:01 UTC, royemosby approved these changes
Other than the need to discuss id's with backend, you're gtg!

2023-06-08 18:02 UTC, Miminiverse commented on src/util/getTime.tsx
> +    const estTime = moment(utcTime).utcOffset(-4).format('hh:mm A');
Thanks for reminding me, I once thought this would be hard to implement but looks like it's not at all, so I will modify it to be based on the user's timezone

2023-06-10 02:29 UTC, frankstepanski approved these changes
Looks good. Don't see anything else that @royemosby didn't see.

2023-06-10 11:55 UTC, Said-laasri approved these changes
Hello @Miminiverse 

<img src="https://media0.giphy.com/media/cdNSp4L5vCU7aQrYnV/giphy.gif"/>

After resolving Conflict :+1: 
this is good to go @Miminiverse  Great Job :1st_place_medal:

2023-06-10 11:55 UTC, merged