Typing
Code-the-Dream-School/cc-prac-team2-front pull request #27
Opened 2023-06-18 18:56 UTC by Miminiverse

This PR contains: 
1/ Update the voice recording so user can listen to their recording before sending it
2/ Add new feature translate text to text
3/ Add new feature typing 
4/ Fix the issue when click into a non-contacted users, it will show a welcome page instead of the chat content of other users

2023-06-19 18:50 UTC, Said-laasri approved these changes
Hey @Miminiverse  Great Job so far!! :100: 

Everything looks great here let's merge this Pr! :1st_place_medal: 

<img src="https://media3.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif"/>

Happy coding !! :+1:

2023-06-19 22:59 UTC, royemosby requested changes
Code looks good but I am uncertain if you intended on checking in your .env file. Please let me know.

2023-06-19 22:59 UTC, royemosby commented on .env
> +VITE_AI_ASSISTANT_CALL=@birdie
These would be secrets that you would want to avoid checking into a repo inside a work project. Are you 100% certain that these details cannot be abused by a 3rd party?

2023-06-19 23:29 UTC, Miminiverse commented on .env
> +VITE_AI_ASSISTANT_CALL=@birdie
This is my mistake I should have put it in the .gitignore. I will put it in the next PR.

2023-06-20 02:29 UTC, royemosby commented on .env
> +VITE_AI_ASSISTANT_CALL=@birdie
👍

2023-06-20 02:30 UTC, royemosby approved these changes
gtg

2023-06-21 12:10 UTC, merged