change .env
Code-the-Dream-School/cc-prac-team2-front pull request #32
Opened 2023-07-08 23:06 UTC by Miminiverse

update .ENV

2023-07-08 23:12 UTC, Said-laasri approved these changes
@Miminiverse  Great Job :+1: 

<img src="https://media0.giphy.com/media/Hc8PMCBjo9BXa/giphy.gif"/>

HAPPY CODING!!!

2023-07-09 15:10 UTC, royemosby requested changes
Please confirm asset url

2023-07-09 15:10 UTC, royemosby commented on index.html
> +    <link rel="icon" href="./src/assests/cockatoo.png" />
Be vary careful with this. That src directory does not get transferred over into the build directory that gets created during the build/deploy process. More information can be found in the Vite docs [here](https://vitejs.dev/guide/assets.html) and [here](https://vitejs.dev/guide/features.html#static-assets). Please confirm that you have a working URL here then ping me on Slack.

2023-07-09 15:16 UTC, frankstepanski commented on index.html
> +    <link rel="icon" href="./src/assests/cockatoo.png" />
Excellent point. Definitely good practice for what changes need to be made to a code-base when you deploy it.

2023-07-09 15:32 UTC, Miminiverse commented on index.html
> +    <link rel="icon" href="./src/assests/cockatoo.png" />
Got it! I moved the image to public folder and use the absolute path.

2023-07-09 16:51 UTC, royemosby commented on index.html
> +    <link rel="icon" href="./src/assests/cockatoo.png" />
👍 schweet!

2023-07-09 16:52 UTC, royemosby approved these changes
GTG!

2023-07-09 17:20 UTC, merged